FROM adoptopenjdk/openjdk8:latest
COPY persona-0.0.1-SNAPSHOT.jar /usr/src/docker/persona-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src/docker
EXPOSE 8089
ENTRYPOINT ["java", "-jar", "/usr/src/docker/persona-0.0.1-SNAPSHOT.jar"]